# Generated by Django 3.2.18 on 2024-05-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('sub_category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'for_lapis_cat_subcat',
            },
        ),
    ]
